### PR TITLE
feat(cursor): added an important feature for the app

### PR DESCRIPTION
**Pull request by kmabika**
Added an important feat 🍍.

### CODE REVIEW

**Review by aobakwewastaken — APPROVED** [review]

**Comment by aobakwewastaken** [comment]
@kmabika you can merge bro

**Comment by kmabika** [comment]
@aobakwewastaken don't have merge access bro 😭

**Comment by aobakwewastaken** [comment]
@kmabika should I add you to the repo?

**Comment by aobakwewastaken** [comment]
Or should I just merge for you @kmabika

**Comment by aobakwewastaken** [comment]
I added you either way @kmabika

**Pull request merged**
